### ISSUE TITLE
Deploy cluster on Azure

### ISSUE THREAD

**Issue by msalvaris** [Microsoft/DLWorkspace#150]
Hi,

I am having some trouble accessing the cluster once I have created it. I follow the instructions from here https://github.com/Microsoft/DLWorkspace/blob/alpha.v1.5/docs/deployment/Azure/Readme.md. My configuration file is as follows.

cluster_name: beowolf

azure_cluster:
  beowolf:
    infra_node_num: 1
    infra_vm_size : Standard_D3_v2
    worker_node_num: 2
    worker_vm_size: Standard_NC6
    azure_location: westus2

UserGroups:
  DLWSAdmins:
    Allowed: [ "<myemail>@gmail.com" ]
    uid : "20000"
    gid : "20001"
  DLWSRegister:
    Allowed: [ "@gmail.com" ]
    uid : "20001-29999"
    gid : "20001"

WebUIregisterGroups: [ "DLWSRegister"]
WebUIauthorizedGroups: [ "DLWSAdmins" ]
WebUIadminGroups: ["DLWSAdmins"]

DeployAuthentications : ["Corp", "Gmail", "Live"]

WinbindServers: []

webuiport: 3080

Everything installs fine as far as I can tell. I run ./deploy.py display and get the url. When I try to access the ui from my browser I get a 502 bad gateway error. I am running the setup on a remote linux vm and trying to access it from my local laptop.

I have tried a number of times and still get the same error. Evidently I am mising something but not sure what. Thanks in advance

**Comment by hongzhili** [comment]
Hi @msalvaris ,

First please run 
```
./deploy.py kubectl get pods 
```
to verify if kubernetes has been deployed and is running. 
If it works, you should see a few running system pods. Please check the log of the webportal pod. We should be able to see the issue from the log.

**Comment by msalvaris** [comment]
The deployment seems to have worked and I can access the portal. I am working off master. Should I work off one of the releases? 

I can't seem to do anything else though. I can't log in or view any of the other pages. Have I configured something wrong based on the configuration I shared in the first post?

**Comment by msalvaris** [comment]
As a further update, I am able to log in using my MS account but it keeps popping up saying I am not an authorised user. I am guessing I need to add my email address to UserGroups?

**Comment by hongzhili** [comment]
Glad to hear it is working now. 
For the gmail login, you need to config google sign-in. please refer to this [doc](https://github.com/Microsoft/DLWorkspace/blob/master/docs/deployment/authentication/gmail.md)
