### ISSUE TITLE
How do I update the list of authorised users?

### ISSUE THREAD

**Issue by msalvaris** [Microsoft/DLWorkspace#165]
How can I update the list of authorised users on a deployed cluster? I can't seem to find the instructions to do that. Any help would be much appreciated :)

**Comment by hongzhili** [comment]
Hi Mat,
You can config the authorized users in config.yaml. Here are [instructions.](https://github.com/Microsoft/DLWorkspace/tree/master/docs/deployment/authentication)

**Comment by msalvaris** [comment]
Thanks, but do I have to run a command once I have alterered the config.yaml file to update things on the cluster?

**Comment by lmiroslaw** [comment]
I have the same question as Mat @msalvaris. I have to update the config.yml with the proper authentication. How do I update the existing deployment with a new configuration?

**Comment by hongzhili** [comment]
You can run the following commands to update the things:
```
./deploy.py webui
./deploy.py kubernetes stop webportal
./deploy.py kubernetes start webportal
```
The first command is to update the config files on your master node and the following commands restart the web portal service.
