### ISSUE TITLE
useFetch has been updated with breaking changes

### ISSUE THREAD

**Issue by alex-cory** [microsoft/DLWorkspace#553]
I was just taking a look at some of the people using `use-http` and saw this repo. Great work! I just wanted to let you know I deprecated `useGet`, `usePost`, `usePatch`, etc. since all that functionality is baked into `useFetch`.

So, instead of
```jsx
  const { data, error, get } = useGet<Job>({
    url: `/api/clusters/${clusterId}/jobs/${jobId}`,
    onMount: true
  });
```
just do this instead
```jsx
  const { data, error, get } = useFetch<Job>({
    url: `/api/clusters/${clusterId}/jobs/${jobId}`,
    onMount: true
  });
```
Looks like you're only using `useGet` in [4 places](https://github.com/microsoft/DLWorkspace/search?q=use-http&unscoped_q=use-http) so should be a quick fix.

**Comment by hongzhili** [comment]
Thanks! Add @Gerhut to follow up.

**Comment by Gerhut** [comment]
Thanks a lot! @alex-cory I am currently migrating them.

**Comment by alex-cory** [comment]
By the way, the infinite loop issue should be fixed. @Gerhut  I'll close this since the update was made :)
